
server:
    port: 9100
spring:
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
            properties:
              hibernate:
                show_sql: true
                format_sql: true
    datasource:
        url: jdbc:h2:mem:testdb
        username: root
        password:
        driveClassName: org.h2.Driver
    jpa:
        show-sql: true
        defer-datasource-initialization: true
        database-plataform: org.hibernate.dialect.H2Dialect
        hibernate.ddl-auto: update
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher